### calibration

In [1]:
# Import required modules
import numpy as np
import os
import glob
import cv2 as cv

In [2]:
# Define the dimensions of checkerboard
CHECKERBOARD = (6, 9)
CHECKERBOARD

(6, 9)

In [3]:
# stop the iteration when specified
# accuracy, epsilon, is reached or
# specified number of iterations are completed.
criteria = (cv.TERM_CRITERIA_EPS +
            cv.TERM_CRITERIA_MAX_ITER, 30, 0.001)
criteria

(3, 30, 0.001)

In [4]:
# Vector for 3D points
threedpoints = []
 
# Vector for 2D points
twodpoints = []

In [5]:
#  3D points real world coordinates
objectp3d = np.zeros((1, CHECKERBOARD[0]
                      * CHECKERBOARD[1],
                      3), np.float32)
objectp3d[0, :, :2] = np.mgrid[0:CHECKERBOARD[0],
                               0:CHECKERBOARD[1]].T.reshape(-1, 2)
objectp3d

array([[[0., 0., 0.],
        [1., 0., 0.],
        [2., 0., 0.],
        [3., 0., 0.],
        [4., 0., 0.],
        [5., 0., 0.],
        [0., 1., 0.],
        [1., 1., 0.],
        [2., 1., 0.],
        [3., 1., 0.],
        [4., 1., 0.],
        [5., 1., 0.],
        [0., 2., 0.],
        [1., 2., 0.],
        [2., 2., 0.],
        [3., 2., 0.],
        [4., 2., 0.],
        [5., 2., 0.],
        [0., 3., 0.],
        [1., 3., 0.],
        [2., 3., 0.],
        [3., 3., 0.],
        [4., 3., 0.],
        [5., 3., 0.],
        [0., 4., 0.],
        [1., 4., 0.],
        [2., 4., 0.],
        [3., 4., 0.],
        [4., 4., 0.],
        [5., 4., 0.],
        [0., 5., 0.],
        [1., 5., 0.],
        [2., 5., 0.],
        [3., 5., 0.],
        [4., 5., 0.],
        [5., 5., 0.],
        [0., 6., 0.],
        [1., 6., 0.],
        [2., 6., 0.],
        [3., 6., 0.],
        [4., 6., 0.],
        [5., 6., 0.],
        [0., 7., 0.],
        [1., 7., 0.],
        [2., 7., 0.],
        [3

In [6]:
# Extracting path of individual image stored
# in a given directory. Since no path is
# specified, it will take current directory
# jpg files alone
images = glob.glob('*.jpg')
images

['calib_radial.jpg']

In [7]:
image = cv.imread('calib_radial.jpg')
print(image.shape)
image

(454, 398, 3)


array([[[ 69,  69,  69],
        [ 68,  68,  68],
        [ 67,  67,  67],
        ...,
        [ 88,  88,  88],
        [ 90,  90,  90],
        [ 92,  92,  92]],

       [[ 70,  70,  70],
        [ 69,  69,  69],
        [ 68,  68,  68],
        ...,
        [ 88,  88,  88],
        [ 90,  90,  90],
        [ 92,  92,  92]],

       [[ 70,  70,  70],
        [ 69,  69,  69],
        [ 68,  68,  68],
        ...,
        [ 88,  88,  88],
        [ 90,  90,  90],
        [ 92,  92,  92]],

       ...,

       [[219, 219, 219],
        [239, 239, 239],
        [238, 238, 238],
        ...,
        [ 90,  90,  90],
        [ 89,  89,  89],
        [ 88,  88,  88]],

       [[167, 167, 167],
        [199, 199, 199],
        [216, 216, 216],
        ...,
        [ 85,  85,  85],
        [ 84,  84,  84],
        [ 83,  83,  83]],

       [[  0,   0,   0],
        [  4,   4,   4],
        [  3,   3,   3],
        ...,
        [  1,   1,   1],
        [  0,   0,   0],
        [  0,   0,   0]]

In [8]:
grayColor = cv.cvtColor(image, cv.COLOR_BGR2GRAY)
print(grayColor.shape)
grayColor

(454, 398)


array([[ 69,  68,  67, ...,  88,  90,  92],
       [ 70,  69,  68, ...,  88,  90,  92],
       [ 70,  69,  68, ...,  88,  90,  92],
       ...,
       [219, 239, 238, ...,  90,  89,  88],
       [167, 199, 216, ...,  85,  84,  83],
       [  0,   4,   3, ...,   1,   0,   0]], dtype=uint8)

In [9]:
print(cv.CALIB_CB_ADAPTIVE_THRESH)
print(cv.CALIB_CB_FAST_CHECK)
print(cv.CALIB_CB_NORMALIZE_IMAGE)

1
8
2


In [10]:
ret, corners = cv.findChessboardCorners(
                grayColor, CHECKERBOARD,
                cv.CALIB_CB_ADAPTIVE_THRESH
                + cv.CALIB_CB_FAST_CHECK +
                cv.CALIB_CB_NORMALIZE_IMAGE)
print(ret)
print(corners.shape)
print(corners)

True
(54, 1, 2)
[[[ 92.54028   56.014145]]

 [[130.00456   52.518837]]

 [[169.2832    49.884296]]

 [[208.53012   47.875313]]

 [[248.70259   46.043774]]

 [[288.1469    45.23031 ]]

 [[ 88.033905  87.45861 ]]

 [[127.47881   84.54666 ]]

 [[167.62128   82.38404 ]]

 [[209.221     80.03681 ]]

 [[250.51486   78.29975 ]]

 [[291.98364   77.17605 ]]

 [[ 83.7952   122.514366]]

 [[124.46601  119.46674 ]]

 [[166.287    117.47988 ]]

 [[209.19469  115.544754]]

 [[252.52414  113.80582 ]]

 [[295.76465  112.69214 ]]

 [[ 79.39718  159.78377 ]]

 [[121.578445 157.51382 ]]

 [[165.14545  155.40175 ]]

 [[209.53223  153.53056 ]]

 [[254.49995  152.2581  ]]

 [[299.47375  150.84784 ]]

 [[ 75.77778  199.54485 ]]

 [[118.95372  197.98636 ]]

 [[163.91402  196.58676 ]]

 [[209.87653  194.73    ]]

 [[256.4185   193.42291 ]]

 [[302.76352  192.2957  ]]

 [[ 72.21573  242.16913 ]]

 [[116.2747   241.38605 ]]

 [[162.62563  240.32915 ]]

 [[210.23659  238.7362  ]]

 [[258.25485  237.59485 ]]

 [[3

In [11]:
threedpoints.append(objectp3d)

In [12]:
corners2 = cv.cornerSubPix(
            grayColor, corners, (11, 11), (-1, -1), criteria)
print(corners2.shape)
corners2

(54, 1, 2)


array([[[ 92.375275,  56.012363]],

       [[130.04256 ,  52.561653]],

       [[169.1642  ,  49.94417 ]],

       [[208.65012 ,  47.59674 ]],

       [[248.90027 ,  46.19838 ]],

       [[288.48013 ,  44.904305]],

       [[ 87.809044,  87.48014 ]],

       [[127.16619 ,  84.44    ]],

       [[167.77275 ,  82.17093 ]],

       [[209.05208 ,  80.06709 ]],

       [[250.53085 ,  78.33484 ]],

       [[292.2044  ,  77.40115 ]],

       [[ 83.88917 , 122.29054 ]],

       [[124.30054 , 119.664764]],

       [[166.42271 , 117.4119  ]],

       [[209.38786 , 115.32952 ]],

       [[252.67465 , 113.79707 ]],

       [[295.73328 , 112.50666 ]],

       [[ 79.51727 , 159.74619 ]],

       [[121.641075, 157.55669 ]],

       [[165.19743 , 155.49591 ]],

       [[209.59422 , 153.6191  ]],

       [[254.50607 , 152.26175 ]],

       [[299.3365  , 150.73917 ]],

       [[ 75.71038 , 199.58174 ]],

       [[118.80619 , 198.13243 ]],

       [[163.98848 , 196.3864  ]],

       [[209.96411 , 194.597

In [13]:
twodpoints.append(corners2)

In [14]:
image = cv.drawChessboardCorners(image,
                                          CHECKERBOARD,
                                          corners2, ret)

In [15]:
cv.imshow('img', image)
cv.waitKey(500)

QObject::moveToThread: Current thread (0x562afa6dc540) is not the object's thread (0x562afaa28160).
Cannot move to target thread (0x562afa6dc540)

QObject::moveToThread: Current thread (0x562afa6dc540) is not the object's thread (0x562afaa28160).
Cannot move to target thread (0x562afa6dc540)

QObject::moveToThread: Current thread (0x562afa6dc540) is not the object's thread (0x562afaa28160).
Cannot move to target thread (0x562afa6dc540)

QObject::moveToThread: Current thread (0x562afa6dc540) is not the object's thread (0x562afaa28160).
Cannot move to target thread (0x562afa6dc540)

QObject::moveToThread: Current thread (0x562afa6dc540) is not the object's thread (0x562afaa28160).
Cannot move to target thread (0x562afa6dc540)

QObject::moveToThread: Current thread (0x562afa6dc540) is not the object's thread (0x562afaa28160).
Cannot move to target thread (0x562afa6dc540)

QObject::moveToThread: Current thread (0x562afa6dc540) is not the object's thread (0x562afaa28160).
Cannot move to tar

-1

In [16]:
cv.destroyAllWindows()
 
h, w = image.shape[:2]
 
 
# Perform camera calibration by
# passing the value of above found out 3D points (threedpoints)
# and its corresponding pixel coordinates of the
# detected corners (twodpoints)
ret, matrix, distortion, r_vecs, t_vecs = cv.calibrateCamera(
    threedpoints, twodpoints, grayColor.shape[::-1], None, None)
 
 
# Displaying required output
print(" Camera matrix:")
print(matrix)
 
print("\n Distortion coefficient:")
print(distortion)
 
print("\n Rotation Vectors:")
print(r_vecs)
 
print("\n Translation Vectors:")
print(t_vecs)

 Camera matrix:
[[539.2263454    0.         199.34737148]
 [  0.         555.93344542 255.03533423]
 [  0.           0.           1.        ]]

 Distortion coefficient:
[[-0.25430223  0.11567822 -0.02212418  0.00692753 -1.38931601]]

 Rotation Vectors:
(array([[-0.37995877],
       [ 0.06212847],
       [-0.01350718]]),)

 Translation Vectors:
(array([[-2.77200198],
       [-4.89951517],
       [13.34236732]]),)


### Undistortion

In [18]:
img = cv.imread('calib_radial.jpg')
h,  w = img.shape[:2]
newcameramtx, roi = cv.getOptimalNewCameraMatrix(matrix, distortion, (w,h), 1, (w,h))

In [19]:
# undistort
dst = cv.undistort(img, matrix, distortion, None, newcameramtx)


# crop the image
x, y, w, h = roi
dst = dst[y:y+h, x:x+w]
cv.imwrite('calibresult.png', dst)

True

In [20]:
# undistort
mapx, mapy = cv.initUndistortRectifyMap(matrix, distortion, None, newcameramtx, (w,h), 5)
dst = cv.remap(img, mapx, mapy, cv.INTER_LINEAR)
# crop the image
x, y, w, h = roi
dst = dst[y:y+h, x:x+w]
cv.imwrite('calibresult2.png', dst)

True