### calibration

In [1]:
# Import required modules
import numpy as np
import os
import glob
import cv2 as cv

In [2]:
# Define the dimensions of checkerboard
CHECKERBOARD = (6, 9)
CHECKERBOARD

(6, 9)

In [3]:
# stop the iteration when specified
# accuracy, epsilon, is reached or
# specified number of iterations are completed.
criteria = (cv.TERM_CRITERIA_EPS +
            cv.TERM_CRITERIA_MAX_ITER, 30, 0.001)
criteria

(3, 30, 0.001)

In [4]:
# Vector for 3D points
threedpoints = []
 
# Vector for 2D points
twodpoints = []

In [5]:
#  3D points real world coordinates
objectp3d = np.zeros((1, CHECKERBOARD[0]
                      * CHECKERBOARD[1],
                      3), np.float32)
objectp3d[0, :, :2] = np.mgrid[0:CHECKERBOARD[0],
                               0:CHECKERBOARD[1]].T.reshape(-1, 2)
objectp3d

array([[[0., 0., 0.],
        [1., 0., 0.],
        [2., 0., 0.],
        [3., 0., 0.],
        [4., 0., 0.],
        [5., 0., 0.],
        [0., 1., 0.],
        [1., 1., 0.],
        [2., 1., 0.],
        [3., 1., 0.],
        [4., 1., 0.],
        [5., 1., 0.],
        [0., 2., 0.],
        [1., 2., 0.],
        [2., 2., 0.],
        [3., 2., 0.],
        [4., 2., 0.],
        [5., 2., 0.],
        [0., 3., 0.],
        [1., 3., 0.],
        [2., 3., 0.],
        [3., 3., 0.],
        [4., 3., 0.],
        [5., 3., 0.],
        [0., 4., 0.],
        [1., 4., 0.],
        [2., 4., 0.],
        [3., 4., 0.],
        [4., 4., 0.],
        [5., 4., 0.],
        [0., 5., 0.],
        [1., 5., 0.],
        [2., 5., 0.],
        [3., 5., 0.],
        [4., 5., 0.],
        [5., 5., 0.],
        [0., 6., 0.],
        [1., 6., 0.],
        [2., 6., 0.],
        [3., 6., 0.],
        [4., 6., 0.],
        [5., 6., 0.],
        [0., 7., 0.],
        [1., 7., 0.],
        [2., 7., 0.],
        [3

In [6]:
# Extracting path of individual image stored
# in a given directory. Since no path is
# specified, it will take current directory
# jpg files alone
images = glob.glob('./data/*.jpg')
images

['./data/right08.jpg',
 './data/right11.jpg',
 './data/left03.jpg',
 './data/right06.jpg',
 './data/left04.jpg',
 './data/left07.jpg',
 './data/right09.jpg',
 './data/left02.jpg',
 './data/right03.jpg',
 './data/right01.jpg',
 './data/left11.jpg',
 './data/right14.jpg',
 './data/left09.jpg',
 './data/left14.jpg',
 './data/right02.jpg',
 './data/right13.jpg',
 './data/left12.jpg',
 './data/right12.jpg',
 './data/left06.jpg',
 './data/right04.jpg',
 './data/left05.jpg',
 './data/left13.jpg',
 './data/right05.jpg',
 './data/right07.jpg',
 './data/left01.jpg',
 './data/left08.jpg']

In [7]:
image = cv.imread(images[0])
print(image.shape)
image

(480, 640, 3)


array([[[  1,   1,   1],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  5,   5,   5],
        [  3,   3,   3],
        [  2,   2,   2],
        ...,
        [  6,   6,   6],
        [  4,   4,   4],
        [  4,   4,   4]],

       [[  0,   0,   0],
        [  2,   2,   2],
        [  4,   4,   4],
        ...,
        [  7,   7,   7],
        [  4,   4,   4],
        [  1,   1,   1]],

       ...,

       [[  0,   0,   0],
        [123, 123, 123],
        [141, 141, 141],
        ...,
        [ 49,  49,  49],
        [ 43,  43,  43],
        [  9,   9,   9]],

       [[ 31,  31,  31],
        [130, 130, 130],
        [128, 128, 128],
        ...,
        [ 40,  40,  40],
        [ 38,  38,  38],
        [  6,   6,   6]],

       [[  0,   0,   0],
        [ 29,  29,  29],
        [  0,   0,   0],
        ...,
        [ 13,  13,  13],
        [ 13,  13,  13],
        [  0,   0,   0]]

In [8]:
grayColor = cv.cvtColor(image, cv.COLOR_BGR2GRAY)
print(grayColor.shape)
grayColor

(480, 640)


array([[  1,   0,   0, ...,   0,   0,   0],
       [  5,   3,   2, ...,   6,   4,   4],
       [  0,   2,   4, ...,   7,   4,   1],
       ...,
       [  0, 123, 141, ...,  49,  43,   9],
       [ 31, 130, 128, ...,  40,  38,   6],
       [  0,  29,   0, ...,  13,  13,   0]], dtype=uint8)

In [9]:
print(cv.CALIB_CB_ADAPTIVE_THRESH)
print(cv.CALIB_CB_FAST_CHECK)
print(cv.CALIB_CB_NORMALIZE_IMAGE)

1
8
2


In [10]:
ret, corners = cv.findChessboardCorners(
                grayColor, CHECKERBOARD,
                cv.CALIB_CB_ADAPTIVE_THRESH
                + cv.CALIB_CB_FAST_CHECK +
                cv.CALIB_CB_NORMALIZE_IMAGE)
print(ret)
print(corners.shape)
print(corners)

True
(54, 1, 2)
[[[149.84738   92.22057 ]]

 [[180.34413   92.123886]]

 [[211.99918   93.90791 ]]

 [[245.50566   96.018486]]

 [[283.03912   98.01248 ]]

 [[321.21417  100.72666 ]]

 [[135.87552  121.935875]]

 [[165.9212   123.67953 ]]

 [[198.38216  126.38809 ]]

 [[233.6892   128.09364 ]]

 [[271.2345   131.82932 ]]

 [[310.96045  135.52339 ]]

 [[121.60144  154.08075 ]]

 [[152.90819  156.56316 ]]

 [[185.4422   160.42516 ]]

 [[220.8879   164.03087 ]]

 [[259.2473   168.53598 ]]

 [[299.5536   173.05763 ]]

 [[108.010605 187.70969 ]]

 [[138.03271  191.79729 ]]

 [[171.7729   196.19325 ]]

 [[207.51189  201.59581 ]]

 [[246.27148  207.3526  ]]

 [[287.4437   212.83247 ]]

 [[ 93.74849  223.28401 ]]

 [[124.74872  228.76869 ]]

 [[157.6031   234.3785  ]]

 [[194.01718  241.06932 ]]

 [[233.33409  248.28055 ]]

 [[275.3498   255.54097 ]]

 [[ 79.97395  259.91245 ]]

 [[110.66664  267.2589  ]]

 [[143.82828  274.05136 ]]

 [[180.65878  282.48172 ]]

 [[219.80487  291.2664  ]]

 [[2

In [11]:
threedpoints.append(objectp3d)

In [12]:
corners2 = cv.cornerSubPix(
            grayColor, corners, (11, 11), (-1, -1), criteria)
print(corners2.shape)
corners2

(54, 1, 2)


array([[[ 92.375275,  56.012363]],

       [[130.04256 ,  52.561653]],

       [[169.1642  ,  49.94417 ]],

       [[208.65012 ,  47.59674 ]],

       [[248.90027 ,  46.19838 ]],

       [[288.48013 ,  44.904305]],

       [[ 87.809044,  87.48014 ]],

       [[127.16619 ,  84.44    ]],

       [[167.77275 ,  82.17093 ]],

       [[209.05208 ,  80.06709 ]],

       [[250.53085 ,  78.33484 ]],

       [[292.2044  ,  77.40115 ]],

       [[ 83.88917 , 122.29054 ]],

       [[124.30054 , 119.664764]],

       [[166.42271 , 117.4119  ]],

       [[209.38786 , 115.32952 ]],

       [[252.67465 , 113.79707 ]],

       [[295.73328 , 112.50666 ]],

       [[ 79.51727 , 159.74619 ]],

       [[121.641075, 157.55669 ]],

       [[165.19743 , 155.49591 ]],

       [[209.59422 , 153.6191  ]],

       [[254.50607 , 152.26175 ]],

       [[299.3365  , 150.73917 ]],

       [[ 75.71038 , 199.58174 ]],

       [[118.80619 , 198.13243 ]],

       [[163.98848 , 196.3864  ]],

       [[209.96411 , 194.597

In [13]:
twodpoints.append(corners2)

In [14]:
image = cv.drawChessboardCorners(image,CHECKERBOARD, corners2, ret)

In [15]:
cv.imshow('img', image)
cv.waitKey(500)

QObject::moveToThread: Current thread (0x562afa6dc540) is not the object's thread (0x562afaa28160).
Cannot move to target thread (0x562afa6dc540)

QObject::moveToThread: Current thread (0x562afa6dc540) is not the object's thread (0x562afaa28160).
Cannot move to target thread (0x562afa6dc540)

QObject::moveToThread: Current thread (0x562afa6dc540) is not the object's thread (0x562afaa28160).
Cannot move to target thread (0x562afa6dc540)

QObject::moveToThread: Current thread (0x562afa6dc540) is not the object's thread (0x562afaa28160).
Cannot move to target thread (0x562afa6dc540)

QObject::moveToThread: Current thread (0x562afa6dc540) is not the object's thread (0x562afaa28160).
Cannot move to target thread (0x562afa6dc540)

QObject::moveToThread: Current thread (0x562afa6dc540) is not the object's thread (0x562afaa28160).
Cannot move to target thread (0x562afa6dc540)

QObject::moveToThread: Current thread (0x562afa6dc540) is not the object's thread (0x562afaa28160).
Cannot move to tar

-1

In [16]:
cv.destroyAllWindows()
 
h, w = image.shape[:2]
 
 
# Perform camera calibration by
# passing the value of above found out 3D points (threedpoints)
# and its corresponding pixel coordinates of the
# detected corners (twodpoints)
ret, matrix, distortion, r_vecs, t_vecs = cv.calibrateCamera(
    threedpoints, twodpoints, grayColor.shape[::-1], None, None)
 
 
# Displaying required output
print(" Camera matrix:")
print(matrix)
 
print("\n Distortion coefficient:")
print(distortion)
 
print("\n Rotation Vectors:")
print(r_vecs)
 
print("\n Translation Vectors:")
print(t_vecs)

 Camera matrix:
[[539.2263454    0.         199.34737148]
 [  0.         555.93344542 255.03533423]
 [  0.           0.           1.        ]]

 Distortion coefficient:
[[-0.25430223  0.11567822 -0.02212418  0.00692753 -1.38931601]]

 Rotation Vectors:
(array([[-0.37995877],
       [ 0.06212847],
       [-0.01350718]]),)

 Translation Vectors:
(array([[-2.77200198],
       [-4.89951517],
       [13.34236732]]),)


### Undistortion

In [18]:
img = cv.imread('calib_radial.jpg')
h,  w = img.shape[:2]
newcameramtx, roi = cv.getOptimalNewCameraMatrix(matrix, distortion, (w,h), 1, (w,h))

In [19]:
# undistort
dst = cv.undistort(img, matrix, distortion, None, newcameramtx)


# crop the image
x, y, w, h = roi
dst = dst[y:y+h, x:x+w]
cv.imwrite('calibresult.png', dst)

True

In [20]:
# undistort
mapx, mapy = cv.initUndistortRectifyMap(matrix, distortion, None, newcameramtx, (w,h), 5)
dst = cv.remap(img, mapx, mapy, cv.INTER_LINEAR)
# crop the image
x, y, w, h = roi
dst = dst[y:y+h, x:x+w]
cv.imwrite('calibresult2.png', dst)

True