### geeksforgeeks

In [1]:
# Import required modules
import numpy as np
import os
import glob
import cv2 as cv

In [2]:
# Define the dimensions of checkerboard
CHECKERBOARD = (6, 9)
CHECKERBOARD

(6, 9)

In [3]:
# stop the iteration when specified
# accuracy, epsilon, is reached or
# specified number of iterations are completed.
criteria = (cv.TERM_CRITERIA_EPS +
            cv.TERM_CRITERIA_MAX_ITER, 30, 0.001)
criteria

(3, 30, 0.001)

In [4]:
# Vector for 3D points
threedpoints = []
 
# Vector for 2D points
twodpoints = []

In [5]:
#  3D points real world coordinates
objectp3d = np.zeros((1, CHECKERBOARD[0]
                      * CHECKERBOARD[1],
                      3), np.float32)
objectp3d[0, :, :2] = np.mgrid[0:CHECKERBOARD[0],
                               0:CHECKERBOARD[1]].T.reshape(-1, 2)
objectp3d

array([[[0., 0., 0.],
        [1., 0., 0.],
        [2., 0., 0.],
        [3., 0., 0.],
        [4., 0., 0.],
        [5., 0., 0.],
        [0., 1., 0.],
        [1., 1., 0.],
        [2., 1., 0.],
        [3., 1., 0.],
        [4., 1., 0.],
        [5., 1., 0.],
        [0., 2., 0.],
        [1., 2., 0.],
        [2., 2., 0.],
        [3., 2., 0.],
        [4., 2., 0.],
        [5., 2., 0.],
        [0., 3., 0.],
        [1., 3., 0.],
        [2., 3., 0.],
        [3., 3., 0.],
        [4., 3., 0.],
        [5., 3., 0.],
        [0., 4., 0.],
        [1., 4., 0.],
        [2., 4., 0.],
        [3., 4., 0.],
        [4., 4., 0.],
        [5., 4., 0.],
        [0., 5., 0.],
        [1., 5., 0.],
        [2., 5., 0.],
        [3., 5., 0.],
        [4., 5., 0.],
        [5., 5., 0.],
        [0., 6., 0.],
        [1., 6., 0.],
        [2., 6., 0.],
        [3., 6., 0.],
        [4., 6., 0.],
        [5., 6., 0.],
        [0., 7., 0.],
        [1., 7., 0.],
        [2., 7., 0.],
        [3

In [6]:
# Extracting path of individual image stored
# in a given directory. Since no path is
# specified, it will take current directory
# jpg files alone
images = glob.glob('*.jpg')
images

['calib_result.jpg']

In [7]:
image = cv.imread('calib_result.jpg')
print(image.shape)
image

(324, 450, 3)


array([[[10, 10, 10],
        [ 9,  9,  9],
        [ 8,  8,  8],
        ...,
        [70, 70, 70],
        [69, 69, 69],
        [69, 69, 69]],

       [[10, 10, 10],
        [ 8,  8,  8],
        [ 8,  8,  8],
        ...,
        [70, 70, 70],
        [70, 70, 70],
        [70, 70, 70]],

       [[10, 10, 10],
        [ 8,  8,  8],
        [ 8,  8,  8],
        ...,
        [70, 70, 70],
        [71, 71, 71],
        [71, 71, 71]],

       ...,

       [[32, 32, 32],
        [37, 37, 37],
        [39, 39, 39],
        ...,
        [71, 71, 71],
        [66, 66, 66],
        [61, 61, 61]],

       [[32, 32, 32],
        [37, 37, 37],
        [39, 39, 39],
        ...,
        [71, 71, 71],
        [65, 65, 65],
        [60, 60, 60]],

       [[30, 30, 30],
        [35, 35, 35],
        [38, 38, 38],
        ...,
        [66, 66, 66],
        [63, 63, 63],
        [59, 59, 59]]], dtype=uint8)

In [8]:
grayColor = cv.cvtColor(image, cv.COLOR_BGR2GRAY)
print(grayColor.shape)
grayColor

(324, 450)


array([[10,  9,  8, ..., 70, 69, 69],
       [10,  8,  8, ..., 70, 70, 70],
       [10,  8,  8, ..., 70, 71, 71],
       ...,
       [32, 37, 39, ..., 71, 66, 61],
       [32, 37, 39, ..., 71, 65, 60],
       [30, 35, 38, ..., 66, 63, 59]], dtype=uint8)

In [9]:
print(cv.CALIB_CB_ADAPTIVE_THRESH)
print(cv.CALIB_CB_FAST_CHECK)
print(cv.CALIB_CB_NORMALIZE_IMAGE)

1
8
2


In [10]:
ret, corners = cv.findChessboardCorners(
                grayColor, CHECKERBOARD,
                cv.CALIB_CB_ADAPTIVE_THRESH
                + cv.CALIB_CB_FAST_CHECK +
                cv.CALIB_CB_NORMALIZE_IMAGE)
print(ret)
print(corners.shape)
print(corners)

True
(54, 1, 2)
[[[163.61986   57.484943]]

 [[189.06319   55.620728]]

 [[214.59303   54.298088]]

 [[240.6728    52.834568]]

 [[267.01486   51.529568]]

 [[293.3811    50.30394 ]]

 [[161.38202   78.8452  ]]

 [[187.39624   77.3602  ]]

 [[213.89505   76.30625 ]]

 [[240.81425   74.69788 ]]

 [[267.8874    73.402855]]

 [[295.24353   72.20186 ]]

 [[158.91414  102.16375 ]]

 [[185.68726  100.82404 ]]

 [[213.02667   99.38793 ]]

 [[240.95543   98.162796]]

 [[269.20676   97.063446]]

 [[297.4882    95.80949 ]]

 [[156.57098  126.48997 ]]

 [[184.26741  125.38869 ]]

 [[212.32367  124.25397 ]]

 [[241.16261  122.87406 ]]

 [[270.0432   122.0327  ]]

 [[299.5466   120.82721 ]]

 [[154.17857  152.42279 ]]

 [[182.50502  151.55756 ]]

 [[211.6092   150.36266 ]]

 [[241.3663   149.25148 ]]

 [[271.17404  148.41637 ]]

 [[301.6403   147.5533  ]]

 [[151.58624  179.98625 ]]

 [[180.8617   179.39424 ]]

 [[211.0426   178.34447 ]]

 [[241.58652  177.63371 ]]

 [[272.5934   176.80739 ]]

 [[3

In [11]:
threedpoints.append(objectp3d)

In [12]:
corners2 = cv.cornerSubPix(
            grayColor, corners, (11, 11), (-1, -1), criteria)
print(corners2.shape)
corners2

(54, 1, 2)


array([[[164.3179  ,  53.63209 ]],

       [[188.63135 ,  53.67367 ]],

       [[215.30748 ,  51.828793]],

       [[240.18837 ,  50.69177 ]],

       [[267.44748 ,  49.05695 ]],

       [[292.9516  ,  47.880978]],

       [[161.30208 ,  78.796326]],

       [[187.34813 ,  77.397934]],

       [[213.91731 ,  76.18415 ]],

       [[240.7799  ,  74.75045 ]],

       [[267.94495 ,  73.44176 ]],

       [[295.49893 ,  72.44866 ]],

       [[158.92378 , 102.02487 ]],

       [[185.76143 , 100.64968 ]],

       [[213.21376 ,  99.373535]],

       [[240.99393 ,  98.100784]],

       [[269.16336 ,  96.91119 ]],

       [[297.42093 ,  95.72883 ]],

       [[156.50089 , 126.542366]],

       [[184.25482 , 125.36454 ]],

       [[212.41748 , 124.126366]],

       [[241.14352 , 123.01468 ]],

       [[270.1829  , 121.888   ]],

       [[299.47217 , 120.78554 ]],

       [[154.09694 , 152.48093 ]],

       [[182.54637 , 151.49297 ]],

       [[211.65033 , 150.34831 ]],

       [[241.34036 , 149.315

In [13]:
twodpoints.append(corners2)

In [14]:
image = cv.drawChessboardCorners(image,
                                          CHECKERBOARD,
                                          corners2, ret)

In [15]:
cv.imshow('img', image)
cv.waitKey(500)

QObject::moveToThread: Current thread (0x55faa5419260) is not the object's thread (0x55faa60f1050).
Cannot move to target thread (0x55faa5419260)

QObject::moveToThread: Current thread (0x55faa5419260) is not the object's thread (0x55faa60f1050).
Cannot move to target thread (0x55faa5419260)

QObject::moveToThread: Current thread (0x55faa5419260) is not the object's thread (0x55faa60f1050).
Cannot move to target thread (0x55faa5419260)

QObject::moveToThread: Current thread (0x55faa5419260) is not the object's thread (0x55faa60f1050).
Cannot move to target thread (0x55faa5419260)

QObject::moveToThread: Current thread (0x55faa5419260) is not the object's thread (0x55faa60f1050).
Cannot move to target thread (0x55faa5419260)

QObject::moveToThread: Current thread (0x55faa5419260) is not the object's thread (0x55faa60f1050).
Cannot move to target thread (0x55faa5419260)

QObject::moveToThread: Current thread (0x55faa5419260) is not the object's thread (0x55faa60f1050).
Cannot move to tar

-1

In [16]:
cv.destroyAllWindows()
 
h, w = image.shape[:2]
 
 
# Perform camera calibration by
# passing the value of above found out 3D points (threedpoints)
# and its corresponding pixel coordinates of the
# detected corners (twodpoints)
ret, matrix, distortion, r_vecs, t_vecs = cv.calibrateCamera(
    threedpoints, twodpoints, grayColor.shape[::-1], None, None)
 
 
# Displaying required output
print(" Camera matrix:")
print(matrix)
 
print("\n Distortion coefficient:")
print(distortion)
 
print("\n Rotation Vectors:")
print(r_vecs)
 
print("\n Translation Vectors:")
print(t_vecs)

 Camera matrix:
[[306.90932227   0.         232.73436779]
 [  0.         329.49901714 237.4364363 ]
 [  0.           0.           1.        ]]

 Distortion coefficient:
[[-0.08150661 -0.33226508 -0.02329393  0.01211733  1.31739346]]

 Rotation Vectors:
(array([[-0.35227402],
       [ 0.03503426],
       [-0.00956213]]),)

 Translation Vectors:
(array([[-2.73252029],
       [-6.45052168],
       [11.85588828]]),)
